### ISSUE TITLE
Dark theme, the highlight color of the modified git file is not obvious enough.

### ISSUE THREAD

**Issue by joe-sky** [zyj1022/vscode-bullish-theme#1]
![image](https://user-images.githubusercontent.com/12705724/112417448-a0dbc180-8d62-11eb-8bd9-c16a72657103.png)

As above, the `start.js` file has been modified, but the color is not much different from other files 😥. 

Looking forward to improvement, thx~

**Comment by zyj1022** [comment]
Thank you, I have modified the color, please update the latest version
